apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: MyCustomResources.percept.azure.windows.net
spec:
  group: percept.azure.windows.net
  names:
    kind: MyCustomResource
    listKind: MyCustomResourceList
    plural: MyCustomResources
    singular: mycustomresource
  scope: Namespaced
  versions:
  - name: v1apha1
    schema:
      openAPIV3Schema:
        properties:
          status:
            description: Status object for the entity.
            properties:
              state:
                type: string
            type: object
          spec:
            description: Specification of the kubernetes object.
            properties:
              name:
                type: string
              properties:
                additionalProperties:
                  type: string
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
