apiVersion: percept.demo.local/v1
kind: Skill
metadata:
  name: <skill_name>
  namespace: <namespace_name>-ns
spec:
  enableVerboseTelemetry : true
  samplingIntervalInHours : 1
  platform : "DeepStream"
  imageUri : "registry.k8s.io/echoserver:1.4"
